name: conf_solv
channels:
  - defaults
  - rdkit
  - schrodinger
  - pytorch
  - conda-forge
dependencies:
  - ase
  - cclib
  - crest
  - einops
  - jupyter
  - matplotlib
  - numpy
  - openbabel
  - pandas
  - py3dmol
  - rdkit==2020.09.1
  - scikit-learn
  - scipy
  - seaborn
  - sympy
