name: ConfSolv
channels:
  - rdkit
  - pytorch
  - pyg
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - ase=3.22.1
  - async-timeout=4.0.2
  - asynctest=0.13.0
  - attrs=21.4.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - boto3=1.24.0
  - botocore=1.27.0
  - bottleneck=1.3.4
  - bravado=11.0.3
  - bravado-core=5.17.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.5.7
  - cachetools=5.0.0
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.1.3
  - cryptography=37.0.1
  - cudatoolkit=10.2.89
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=4.4.0
  - defusedxml=0.7.1
  - einops=0.4.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - expat=2.4.4
  - flask=2.1.2
  - fontconfig=2.13.1
  - freetype=2.11.0
  - frozenlist=1.3.0
  - fsspec=2022.5.0
  - future=0.18.2
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - google-auth=2.6.6
  - google-auth-oauthlib=0.4.6
  - grpcio=1.38.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_metadata=1.5.0
  - importlib_resources=5.2.0
  - intel-openmp=2022.0.1
  - ipykernel=6.9.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - itsdangerous=2.1.2
  - jedi=0.18.1
  - jinja2=3.0.3
  - jmespath=1.0.0
  - joblib=1.1.0
  - jpeg=9e
  - jsonref=0.2
  - jsonschema=4.4.0
  - jupyter=1.0.0
  - jupyter_client=7.2.2
  - jupyter_console=6.4.3
  - jupyter_core=4.9.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.4.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libboost=1.73.0
  - libcblas=3.9.0
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libprotobuf=3.18.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - markdown=3.3.7
  - markupsafe=2.0.1
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2022.0.1
  - monotonic=1.5
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - msgpack-python=1.0.3
  - multidict=6.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.13
  - nbconvert=6.4.3
  - nbformat=5.3.0
  - ncurses=6.3
  - neptune-client=0.16.3
  - nest-asyncio=1.5.5
  - networkx=2.5.1
  - nglview=3.0.4
  - notebook=6.4.8
  - numexpr=2.8.0
  - numpy=1.21.6
  - oauthlib=3.2.0
  - openpyxl=3.0.10
  - openssl=1.1.1t
  - packaging=21.3
  - pandas=1.3.5
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.2
  - pixman=0.40.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.18.0
  - psutil=5.9.1
  - ptyprocess=0.7.0
  - py-boost=1.73.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pydeprecate=0.3.2
  - pyg=2.0.4
  - pygments=2.11.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.7.13
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python-louvain=0.15
  - python_abi=3.7
  - pytorch=1.11.0
  - pytorch-cluster=1.6.0
  - pytorch-lightning=1.6.1
  - pytorch-mutex=1.0
  - pytorch-scatter=2.0.9
  - pytorch-sparse=0.6.13
  - pytorch-spline-conv=1.2.1
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - qtconsole=5.3.0
  - qtpy=2.0.1
  - rdkit=2020.09.1.0
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - s3transfer=0.6.0
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - seaborn-base=0.11.2
  - send2trash=1.8.0
  - setuptools=59.5.0
  - simplejson=3.17.6
  - sip=4.19.25
  - six=1.16.0
  - smmap=3.0.5
  - soupsieve=2.3.1
  - sqlite=3.38.3
  - statsmodels=0.13.2
  - swagger-spec-validator=2.7.4
  - sympy=1.10.1
  - tensorboard=2.9.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - terminado=0.13.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - torchmetrics=0.9.0
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.3.2
  - werkzeug=2.1.2
  - wheel=0.37.1
  - widgetsnbextension=3.5.2
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - memory-profiler==0.61.0
